[project]
name = "py-borderless-games-and-apps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psutil>=7.0.0",
    "pyinstaller>=6.13.0",
    "pywin32>=310",
]
